[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "solidity-examples/=lib/solidity-examples/",
]

[fmt]
line_length = 100
tab_width = 4
